### ISSUE TITLE
Exports is not defined

### ISSUE THREAD

**Issue by gvsrini** [quandl/quandlism#65]
When I run the application, I get these errors in the console:

```
Uncaught ReferenceError: exports is not defined
Uncaught ReferenceError: quandlism is not defined
```

I have read that this is caused because Browserify is not used. I have no clue how to plug that into this app.

Any help will be highly appreciated.

**Comment by jbyck** [comment]
I'm sorry, but this project is no longer under active development and we are no longer supporting it. I've updated the README to reflect that. Please feel free to fork and continue the development. We will be closing the repository in 1 month.
